### ISSUE TITLE
Na lista de autorização - atualizar a lista do histórico com ajax

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/quotas#62]

**Comment by thiagogomesverissimo** [comment]
@ricardfo a lista do histórico não está sendo atualizada dinamincamente. Chegou a mexer nessa issue?

**Comment by ricardfo** [comment]
Não mexi.

**Comment by ricardfo** [comment]
@thiagogomesverissimo cheguei a fazer e depois foi pedido para parar porque estava tendo muitas requisições no servidor.
