### ISSUE TITLE
[WIP] Implementando laravel-printing para impressão pela web

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/quotas#72]
https://randallwilk.dev/docs/laravel-printing/v3/installation

- [x] Considerar o arquivo de upload (Thiago)
- [x] Validar que o arquivo é um pdf (Thiago)
- [x] Contabilizar páginas com pdfinfo (Thiago)
- [x] Na página de enviar impressão mostrar somente a lista de impressoras que o usuário tem acesso (Thiago)
- [x] Implementar opção de frente e verso, na borda maior e na borda menor (will)

Prioridade baixa:

- [x] #76

**Comment by wgnann** [comment]
não tem como trocar o nome de usuário no job, pois o sistema usa as credenciais fornecidas para o CUPS

o resto foi resolvido
